version: '3.8'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.10.2
    container_name: tracebuddy-es
    environment:
      - node.name=es01
      - cluster.name=tracebuddy-cluster
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - "9200:9200"
    volumes:
      - es_data:/usr/share/elasticsearch/data
    networks:
      - tracebuddy-net

  redis:
    image: redis:7.2
    container_name: tracebuddy-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - tracebuddy-net

  kibana:
    image: docker.elastic.co/kibana/kibana:8.10.2
    container_name: tracebuddy-kibana
    ports:
      - "5601:5601"
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    depends_on:
      - elasticsearch
    networks:
      - tracebuddy-net

volumes:
  es_data:
  redis_data:

networks:
  tracebuddy-net:
    driver: bridge
