version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: tracebuddy-postgres
    environment:
      - POSTGRES_USER=tracebuddy
      - POSTGRES_PASSWORD=tracebuddy
      - POSTGRES_DB=tracebuddy
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - tracebuddy-net

  redis:
    image: redis:7.2
    container_name: tracebuddy-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - tracebuddy-net

  

volumes:
  pg_data:
  redis_data:

networks:
  tracebuddy-net:
    driver: bridge
